cheat_sheets/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cheats.urls',  namespace='cheats'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cheats/urls.py
from django.urls import path

from cheats.views import CheatListView, CategoryListView, CheatDetailView, CheatCreateView, CheatUpdateView, \
    CategoryCreateView, CheatDeleteView, CategoryDeleteView

app_name = 'cheats'

urlpatterns = [
    path('', CategoryListView.as_view(),  name='categories'),
    path('cheats/', CheatListView.as_view(), name='cheats'),
    path('cheat/<int:pk>/', CheatDetailView.as_view(), name='cheat'),
    path('cheat/create/', CheatCreateView.as_view(), name='cheat_create'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/create/', CategoryCreateView.as_view(), name='category_update'),
    path('cheat/<int:pk>/update/', CheatUpdateView.as_view(), name='cheat_update'),
    path('cheat/<int:pk>/delete/', CheatDeleteView.as_view(), name='cheat_delete'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category_delete'),
]

cheats/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='название')
    logo = models.ImageField(upload_to='logo', verbose_name='логотип')

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.title


CHEAT_DRAFT = 'draft'
CHEAT_PUBLISHED = 'published'
CHEAT_EDITED = 'edited'


class Cheat(models.Model):
    STATUSES = (
        (CHEAT_DRAFT, 'черновик'),
        (CHEAT_PUBLISHED, 'опубликовано'),
        (CHEAT_EDITED, 'редактируется')
    )
    category = models.ForeignKey(Category, verbose_name='категория', on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=100, verbose_name='заголовок')
    body = models.TextField(verbose_name='текст')
    status = models.CharField(max_length=12, choices=STATUSES, verbose_name='статус')
    created_at = models.DateTimeField(auto_now=True, verbose_name='время создания')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='время редактирования')

    class Meta:
        verbose_name = 'шпаргалка'
        verbose_name_plural = 'шпаргалки'

    def __str__(self):
        return self.title

cheats/forms.py
from django import forms

from cheats.models import Category


class CheatForm(forms.Form):
    category = forms.SlugField()
    title = forms.CharField()
    body = forms.CharField(widget=forms.Textarea)
    status = forms.ChoiceField()

cheats/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from cheats.models import Cheat, Category


class CheatListView(ListView):
    model = Cheat
    extra_context = {
        'title': 'Шпаргалки'
    }

    def get(self, request,  *args, **kwargs):
        category = request.GET.get('category', None)
        if category:
            self.queryset = self.get_queryset().filter(category=category)
        return super().get(request, args, kwargs)

    def get_context_data(self, **kwargs):
        title = self.queryset.select_related().first().category.title if self.queryset else None
        return super().get_context_data(category=title, **kwargs)


class CheatDetailView(DetailView):
    model = Cheat

    def get_context_data(self, **kwargs):
        return super().get_context_data(title=self.object.title, **kwargs)


class CheatCreateView(CreateView):
    model = Cheat
    fields = ('title', 'category', 'body', 'status')
    success_url = '/'
    extra_context = {
        'title': 'Добавить шпаргалку'
    }


class CheatUpdateView(UpdateView):
    model = Cheat
    fields = ('title', 'category', 'body', 'status')
    success_url = '/'
    extra_context = {
        'title': 'Редактировать шпаргалку'
    }


class CheatDeleteView(DeleteView):
    model = Cheat
    success_url = '/'

    def get_context_data(self, **kwargs):
        return super().get_context_data(title=f'Удалить {self.object.title}', **kwargs)


class CategoryListView(ListView):
    model = Category
    extra_context = {
        'title': 'Категории'
    }


class CategoryDetailView(DetailView):
    model = Category

    def get_context_data(self, **kwargs):
        return super().get_context_data(title=self.object.title, **kwargs)


class CategoryCreateView(CreateView):
    model = Category
    fields = ('title', 'logo')
    success_url = '/'
    extra_context = {
        'title': 'Добавить категрию'
    }


class CategoryDeleteView(DeleteView):
    model = Category
    success_url = '/'

    def get_context_data(self, **kwargs):
        return super().get_context_data(title=f'Удалить {self.object.title}', **kwargs)

cheats/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet"  crossorigin="anonymous">
    <title>{{ title }}</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-light bg-light">
          <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'cheats:categories' %}">Все категории</a>
              <a class="navbar-brand" href="{% url 'cheats:category_create' %}">+Категория</a>
          </div>
        </nav>
        <nav class="navbar navbar-light bg-light">
          <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'cheats:cheats' %}">Все шпаргалки</a>
              <a class="navbar-brand" href="{% url 'cheats:cheat_create' %}">+Шпаргалка</a>
          </div>
        </nav>
        <h1>{{title}}{% if category %}: {{category}}{% endif %}</h1>
        {% block content %}

        {% endblock %}
    </div>
    <script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
</body>
</html>

cheats/templates/cheats/category_confirm_delete.html
{% extends 'base.html'%}
{% block content %}
<body>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Удалить">
    <a class="navbar-brand" href="{% url 'cheats:cheats' %}">Отменить</a>
</form>
{% endblock %}

cheats/templates/cheats/category_form.html
{% extends 'base.html'%}
{% block content %}
<body>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить">
</form>
{% endblock %}

cheats/templates/cheats/category_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
    {% for object in object_list %}

            <div class="card col-md-3">
              <img src="/media/{{ object.logo }}" class="card-img-top" alt="...">
              <div class="card-body">
                  <a class="card-text" href = "{% url 'cheats:cheats' %}?category={{object.id}}">{{object.title}}</a>
                  <a class="card-text" href = "{% url 'cheats:category_delete' object.id %}">Удалить</a>
              </div>
            </div>

    {% endfor %}
        </div>
    </div>
{% endblock %}

cheats/templates/cheats/cheat_confirm_delete.html
{% extends 'base.html'%}
{% block content %}
<body>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Удалить">
    <a class="navbar-brand" href="{% url 'cheats:cheats' %}">Отменить</a>
</form>
{% endblock %}

cheats/templates/cheats/cheat_detail.html
{% extends 'base.html' %}

{% block content %}
    <p>{{object.body}}</p>
{% endblock %}

cheats/templates/cheats/cheat_form.html
{% extends 'base.html'%}
{% block content %}
<body>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Добавить">
</form>
{% endblock %}

cheats/templates/cheats/cheat_list.html
{% extends 'base.html' %}


{% block content %}
<div class="row">
    {% for object in object_list %}
        <div class="card col-md-4">
            <h3><a href="{% url 'cheats:cheat' object.id%}">{{object.title}}</a></h3>
          <div class="card-body">
              <p class="card-text" >{{object.body|slice:20}}...</p>
              <a href="{% url 'cheats:cheat_update' object.id %}">Редактировать</a>
              <a href="{% url 'cheats:cheat_delete' object.id %}">Удалить</a>
          </div>
        </div>
    {% endfor %}
</div>
{% endblock %}